---
- name: "update apt packages"
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: true
  apt: 
    upgrade: yes

- name: "remove dependencies"
  become: yes
  apt: 
    autoremove: yes

- name: "install dependencies"
  become: yes
  apt: 
    pkg: 
      - nodejs
      - npm
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  apt: 
    install: pm2
    global: yes
    production: yes
    state: present

