---
- name: "create a new directory"
  become: yes
  file:
    path: ~/backend_temp/
    state: directory

- name: "extract backend sources"
  become: yes
  unarchive:
    src: ./backend.tar.gz
    dest: ~/backend_temp/

- name: "install npm"
  become: yes
  command: npm install
  args:
    chdir: ~/backend_temp/

- name: "start pm2"
  become: yes
  command: pm2 start npm -- run start
  args:
    chdir: ~/backend_temp/
