---
- name: "update apt packages"
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: true
  apt: 
    upgrade: yes

- name: "remove dependencies"
  become: yes
  apt: 
    autoremove: yes

- name: "install dependencies"
  become: yes
  apt: 
    pkg: 
      - nodejs
      - npm
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm: 
    name: pm2
    global: yes
    production: yes
    state: present

- name: "create a new directory"
  become: yes
  file:
    path: /home/ubuntu/backend_app/
    state: directory

- name: "extract backend sources"
  become: yes
  unarchive:
    src: /root/project/backend.tar.gz
    dest: /home/ubuntu/backend_app/

- name: "install npm"
  become: yes
  command: npm install
  args:
    chdir: /home/ubuntu/backend_app/backend/

- name: "install npm"
  become: yes
  command: npm run build-prod
  args:
    chdir: /home/ubuntu/backend_app/backend/

- name: "Start backend with pm2"
  shell: |
    export ENVIRONMENT=production
    export NODE_ENV=production
    export TYPEORM_HOST="{{lookup ('env', 'TYPEORM_HOST')}}"
    export TYPEORM_ENTITIES="{{lookup ('env', 'TYPEORM_ENTITIES')}}"
    export TYPEORM_USERNAME="{{lookup ('env', 'TYPEORM_USERNAME')}}"
    export TYPEORM_PASSWORD="{{lookup ('env', 'TYPEORM_PASSWORD')}}"
    export TYPEORM_DATABASE="{{lookup ('env', 'TYPEORM_DATABASE')}}"
    pm2 start main.js --name udapeople-backend
  args:
    chdir: /home/ubuntu/backend_app/backend/

- name: "start pm2"
  become: yes
  command: pm2 start npm -- run start
  args:
    chdir: /home/ubuntu/backend_app/backend/

